#!/usr/bin/env Rscript
# Minimal BlankCox training via the published R interface (reticulate -> Python).
#
# Bypasses DEGAS_preprocessing() and run_DEGAS_SCST() entirely; calls the
# Python backend's bagging_all_results() directly. Expects pre-normalized
# expression matrices in [0, 1] and survival phenotype as [time, status].
#
# Input:  sim_data.npz (generated by simulate_data.py)
# Output: risk_R.csv   (columns: index, hazard) for comparison with Python path

suppressPackageStartupMessages(library(reticulate))

# Pin threading before torch is loaded (DEGAS_python -> torch). This cuts
# intra-op parallelism as a source of non-determinism during training.
Sys.setenv(OMP_NUM_THREADS = "1", MKL_NUM_THREADS = "1")

script_path <- local({
    args <- commandArgs(trailingOnly = FALSE)
    hit <- sub("^--file=", "", grep("^--file=", args, value = TRUE))
    if (length(hit)) normalizePath(hit, mustWork = FALSE) else ""
})
here <- if (nzchar(script_path)) dirname(script_path) else getwd()

np <- import("numpy", convert = FALSE)
DEGAS_python <- import("DEGAS_python")
import("torch")$set_num_threads(1L)

# Keep the numpy arrays on the Python side (convert=FALSE). If we let
# reticulate auto-convert to R matrices, the subsequent round-trip back
# to numpy produces F-contiguous float64 buffers and silently promotes
# pat_lab from int64 to float64. That stride / dtype drift is enough to
# desync from the pure-Python path.
npz <- np$load(file.path(here, "sim_data.npz"))
pat_expr <- np$ascontiguousarray(npz[["pat_expr"]])
pat_lab  <- np$ascontiguousarray(npz[["pat_lab"]], dtype = np$int64)
sc_expr  <- np$ascontiguousarray(npz[["sc_expr"]])

cat(sprintf("pat_expr=%s  pat_lab=%s  sc_expr=%s\n",
            py_str(pat_expr$shape),
            py_str(pat_lab$shape),
            py_str(sc_expr$shape)))

opt <- DEGAS_python$BlankCox_opt
opt$save_dir        <- file.path(here, "out_R")
opt$data_name       <- "minimal_test_R"
opt$tot_seeds       <- 2L
opt$tot_iters       <- 100L
opt$pat_batch_size  <- 20L
opt$batch_size      <- 100L
opt$save_freq       <- 50L

if (!dir.exists(opt$save_dir)) dir.create(opt$save_dir, recursive = TRUE)

results <- DEGAS_python$bagging_all_results(
    opt,
    pat_expr,
    pat_lab,
    sc_expr,
    sc_lab_mat = NULL
)

# `results` comes back as a pandas DataFrame proxy (reticulate doesn't
# auto-convert pandas); pull the two columns of interest as R vectors.
risk <- data.frame(
    index  = as.integer(results$`__getitem__`("index")$to_numpy()),
    hazard = as.numeric(results$`__getitem__`("hazard")$to_numpy())
)
risk <- risk[order(risk$index), ]

out_csv <- file.path(here, "risk_R.csv")
write.csv(risk, out_csv, row.names = FALSE)
cat(sprintf("wrote %s (%d rows)\n", out_csv, nrow(risk)))

cat("head(risk):\n"); print(utils::head(risk))
centered <- risk$hazard - median(risk$hazard)
cat("summary(hazard - median(hazard)):\n"); print(summary(centered))
